/* $CwuRes: src/regi/www/webapps/rnreg/src/ArpCache.h,v 1.1 2003/02/20 00:37:34 hartd Exp $ */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArpCache */

#ifndef _Included_ArpCache
#define _Included_ArpCache
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArpCache
 * Method:    getmac
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ArpCache_getmac
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
